### ISSUE TITLE
Search codes, libraries and syntax used for bush buttons

### ISSUE THREAD

**Issue by wilaz-laz98** [wilaz-laz98/ElderAid-MicroprocessorProject#12]

**Comment by khawlanouam** [comment]
Programme :
from machine import Pin, UART
import time
 
# Configuration du bouton poussoir
button_pin = Pin(4, Pin.IN, Pin.PULL_DOWN)  # GPIO 4 configuré en entrée avec pull-down interne
 
# Configuration du module GSM (SIM800L)
uart = UART(1, baudrate=9600, tx=17, rx=16)  # TX sur GPIO 17, RX sur GPIO 16
 
# Variables pour la détection de double-clic
last_press_time = 0
double_click_threshold = 0.5  # Intervalle max entre deux clics (en secondes)
 
def send_alert():
   """
   Fonction pour envoyer une alerte via le module GSM.
   """
   print("ALERTE DÉCLENCHÉE ! Double-clic détecté.")
   uart.write('AT+CMGF=1\r')  # Mode texte
   time.sleep(1)
   uart.write('AT+CMGS="+212600000000"\r')  # Remplacez par un numéro valide
   time.sleep(1)
   uart.write("Alerte d'urgence déclenchée!\r")
   uart.write(chr(26))  # Ctrl+Z pour envoyer le message
   time.sleep(1)
 
def check_button():
   """
   Fonction principale pour surveiller l'état du bouton poussoir.
   """
   global last_press_time
   
   if button_pin.value() == 1:  # Bouton pressé
       current_time = time.time()
       if current_time - last_press_time <= double_click_threshold:
           # Double-clic détecté
           send_alert()[3eme tache archi.docx](https://github.com/user-attachments/files/18212590/3eme.tache.archi.docx)

       last_press_time = current_time  # Mise à jour du temps du dernier clic
       time.sleep(0.2)  # Anti-rebond pour éviter des lectures multiples
 
# Boucle principale
print("Système prêt. Appuyez deux fois sur le bouton pour déclencher une alerte.")
while True:
   check_button()
