### ISSUE TITLE
search codes, libraries and syntax used for MPU

### ISSUE THREAD

**Issue by wilaz-laz98** [wilaz-laz98/ElderAid-MicroprocessorProject#13]

**Comment by lazarwalae** [comment]
LIBRARIES :
  -micropython
  -mpu6500
  -ak8963
src=**https://github.com/tuupola/micropython-mpu9250/blob/master/mpu9250.py**  INDEX : devname  :  tuupola.

CODE:
from machine import Pin, I2C
from time import sleep

# Initialize I2C
i2c = I2C(0, scl=Pin(22), sda=Pin(21))

# MPU9250 address
MPU9250_ADDRESS = 0x68

# Initialize MPU9250 registers
def mpu9250_init():
    # Wake up the MPU9250
    i2c.writeto_mem(MPU9250_ADDRESS, 0x6B, b'\x00')
    # Configure gyroscope range
    i2c.writeto_mem(MPU9250_ADDRESS, 0x1B, b'\x00')  # ±250°/s
    # Configure accelerometer range
    i2c.writeto_mem(MPU9250_ADDRESS, 0x1C, b'\x00')  # ±2g

def read_raw_data(addr):
    # Read two bytes of data and convert to integer
    high = i2c.readfrom_mem(MPU9250_ADDRESS, addr, 1)
    low = i2c.readfrom_mem(MPU9250_ADDRESS, addr + 1, 1)
    value = (high[0] << 8) | low[0]
    if value > 32768:
        value -= 65536
    return value

# Get sensor data
def read_mpu9250():
    accel_x = read_raw_data(0x3B)
    accel_y = read_raw_data(0x3D)
    accel_z = read_raw_data(0x3F)
    gyro_x = read_raw_data(0x43)
    gyro_y = read_raw_data(0x45)
    gyro_z = read_raw_data(0x47)

    accel = {
        "x": accel_x / 16384.0,  # Scale for ±2g
        "y": accel_y / 16384.0,
        "z": accel_z / 16384.0
    }
    gyro = {
        "x": gyro_x / 131.0,  # Scale for ±250°/s
        "y": gyro_y / 131.0,
        "z": gyro_z / 131.0
    }

    return accel, gyro

# Main
mpu9250_init()

while True:
    accel, gyro = read_mpu9250()
    print("Accelerometer: ", accel)
    print("Gyroscope: ", gyro)
    sleep(1)
