### ISSUE TITLE
search codes, libraries and syntax used for SIM module

### ISSUE THREAD

**Issue by wilaz-laz98** [wilaz-laz98/ElderAid-MicroprocessorProject#15]

**Comment by Rihaaabe** [comment]
**MicroPython Code Example**

- To test the connection:

from machine import UART
from time import sleep

# Initialize UART
uart = UART(2, baudrate=9600, tx=17, rx=16)  # Adjust pins if needed

# Test sending an AT command
def send_at_command(command, delay=1):
    uart.write(command + "\r\n")
    sleep(delay)
    if uart.any():
        response = uart.read().decode('utf-8')
        print(response)
    else:
        print("No response.")

send_at_command("AT")  # Send basic AT command

**Debugging Tips :**

- Check voltage levels on the SIM800L (must be 3.7V).
- Ensure the SIM800L module's LED blinks after powering up.
- Test UART communication by sending AT commands and checking for responses.
